version: '3.8'

services:
  http1:
    build: .
    ports:
      - "8881:8881"
    environment:
      SERVER_PORT: 8881
      SERVER_HTTP2_ENABLED: 'false'

  http2:
    build: .
    ports:
      - "8882:8882"
    environment:
      SERVER_PORT: 8882
      SERVER_HTTP2_ENABLED: 'true'